info:
    app:
        description: Spring Boot Advanced training
        name: Spring Boot Master class
        version: 1.0.0
    company:
        name: Company Name
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: health,info,prometheus
    info:
        env:
            enabled: true
server:
    error:
        include-binding-errors: always
        include-message: always
        include-stacktrace: ON_PARAM
spring:
    datasource:
        driverClassName: org.h2.Driver
        password: hello
        url: jdbc:h2:mem:testdb-dev-environment
        username: dev
    h2:
        console:
            enabled: true
            path: /h2-dev
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
    main:
        banner-mode: 'off'
